# Configuration options for dependency updates
# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Shanghai"
    assignees:
      - "Runrioter"
    labels:
      - "dependencies"
